# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170623_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('1', 'Page'), ('2', 'Event'), ('3', 'Article')], default='1', max_length=9),
        ),
    ]
